CREATE DATABASE liczniki;
\c liczniki;
CREATE TABLE tabelalicznikow(
ID SERIAL PRIMARY KEY NOT NULL,
ID KLIENTA INTEGER NOT NULL,
MIESIACROK INTEGER NOT NULL,
KODTARYFY CHAR NOT NULL,
ZUZYCIEKW NUMERIC(15,1),
CENAJEDN NUMERIC(15,2),
KOSZT NUMERIC(15,2),
KOMENTARZ VARCHAR(100)
);
CREATE TABLE tabelawzorow(
ID SERIAL PRIMARY KEY NOT NULL,
KOD VARCHAR(1),
WZOR VARCHAR(100)
);
\copy tabelawzorow(ID,KOD,WZOR) FROM wzory.txt